#!/usr/bin/env python3
"""Build the const-vc-dd100 suite: const-vc with the weak crust cut off at 100 km.

const-vc-dd100 is a one-term ablation of const-vc.  The crust compositional
field's first phase transition (below which "ocrust" takes the background
mantle rheology, i.e. the slab decouples from the wedge no deeper than this)
moves from 150 km to 100 km -- a prescribed maximum decoupling depth.  Every
other line of every .prm is identical, and the design is the same 400-point
Latin hypercube (data/params/params-list.const-vc-dd100.* are copies of the
const-vc lists), so run_XXX pairs with const-vc run_XXX.

Rather than regenerating the plate input files (identical for paired runs;
~47 MB per run, 19 GB per suite), this script derives each run from the
existing const-vc run-inputs:
  * reads subd-model-runs/const-vc/run-inputs/run_XXX/run_XXX.prm, replaces
    exactly one line (the ocrust phase-transition depths), and writes
    subd-model-runs/const-vc-dd100/run-inputs/run_XXX/run_XXX.prm;
  * hard-links inputs/* from the const-vc run (falls back to copying if the
    link fails, e.g. across filesystems) -- no extra disk locally, plain
    files when rsync'd to TACC;
  * copies run_one.slurm / submit_from_list.sh / submit_rolling.sh with the
    BASE_DIR suite name const-vc-new -> const-vc-dd100.
It asserts the .prm diff is exactly one line per run.  The reference
template data/ref-model/model_template_fixed-trench.const-vc-dd100.prm is
kept in step for the record (and for build_runs.const-vc.py-style
regeneration if the const-vc run-inputs are ever absent).

Usage:  python src/build-numerical-mods/build_runs.const-vc-dd100.py
PI decision 2026-09-10 (fixed 100 km; shallower cutoffs make the plates
merge).  Not part of the NSF proposal suites.
"""
import os, shutil, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC_SUITE, NEW_SUITE = "const-vc", "const-vc-dd100"
SRC_DIR = ROOT / "subd-model-runs" / SRC_SUITE / "run-inputs"
OUT_DIR = ROOT / "subd-model-runs" / NEW_SUITE / "run-inputs"
OLD_LINE = "ocrust: 150e3|660e3"
NEW_LINE = "ocrust: 100e3|660e3"
OLD_BASE, NEW_BASE = "production-runs_v2/const-vc-new", f"production-runs_v2/{NEW_SUITE}"
SCRIPTS = ["run_one.slurm", "submit_from_list.sh", "submit_rolling.sh"]

if not SRC_DIR.is_dir():
    sys.exit(f"const-vc run-inputs not found at {SRC_DIR}; regenerate them first "
             "(build_runs.const-vc.py) or adapt this script to the template.")
OUT_DIR.mkdir(parents=True, exist_ok=True)

runs = sorted(p for p in SRC_DIR.glob("run_*") if p.is_dir())
n_ok = 0
for src_run in runs:
    name = src_run.name
    src_prm = src_run / f"{name}.prm"
    if not src_prm.is_file():
        print(f"  skip {name}: no {src_prm.name}")
        continue
    text = src_prm.read_text()
    if text.count(OLD_LINE) != 1:
        sys.exit(f"{src_prm}: expected exactly one '{OLD_LINE}', found {text.count(OLD_LINE)}")
    new = text.replace(OLD_LINE, NEW_LINE)
    new = new.replace("# This file is auto-generated by build_runs.const-vc.py",
                      "# This file is auto-generated by build_runs.const-vc-dd100.py\n"
                      f"# Derived from {SRC_SUITE}/run-inputs/{name}/{name}.prm: identical except the\n"
                      "# ocrust phase-transition depth 150e3 -> 100e3 (max decoupling depth 100 km).")
    changed = [i for i, (a, b) in enumerate(zip(text.splitlines(), new.splitlines())) if a != b]
    # header gained two lines, so compare bodies after the header comment block
    body_old = text.split("\nset Dimension", 1)[1]
    body_new = new.split("\nset Dimension", 1)[1]
    diffs = [i for i, (a, b) in enumerate(zip(body_old.splitlines(), body_new.splitlines())) if a != b]
    assert len(diffs) == 1 and len(body_old.splitlines()) == len(body_new.splitlines()), \
        f"{name}: body differs in {len(diffs)} lines, expected 1"

    dst_run = OUT_DIR / name
    (dst_run / "inputs").mkdir(parents=True, exist_ok=True)
    (dst_run / f"{name}.prm").write_text(new)
    for f in sorted((src_run / "inputs").iterdir()):
        dst = dst_run / "inputs" / f.name
        if dst.exists():
            continue
        try:
            os.link(f, dst)
        except OSError:
            shutil.copy2(f, dst)
    n_ok += 1

for s in SCRIPTS:
    src = SRC_DIR / s
    if src.is_file():
        t = src.read_text()
        assert OLD_BASE in t, f"{s}: BASE_DIR pattern not found"
        (OUT_DIR / s).write_text(t.replace(OLD_BASE, NEW_BASE))
        shutil.copymode(src, OUT_DIR / s)

print(f"Finished: {n_ok} run directories under {OUT_DIR} "
      f"(prm: one-line change {OLD_LINE!r} -> {NEW_LINE!r}; inputs hard-linked from {SRC_SUITE}); "
      f"scripts: {', '.join(SCRIPTS)} with BASE_DIR -> {NEW_BASE}")
