#!/usr/bin/env python3
"""Submission list for the const-vc-dd100 full set: the const-vc design filtered to dip_int >= DIP_MIN.

PI decision 2026-09-15: low-dip slabs flatten along the 100 km crust cutoff (pilot: flattening at
dip 25-26 deg by 5 Myr, none at 38), so dd100 is run only for dip >= 35 deg. Filtering (rather than
redrawing the LHS) keeps run_XXX paired with const-vc and leaves the marginals uniform (checked:
KS p >= 0.98, |corr| <= 0.09, all 4x4 pairwise cells filled at n = 320). Pilot runs are excluded
(already submitted). The 35-40 deg band goes first, ascending dip, so it can be checked early.

Usage: python src/build-numerical-mods/make_submit_list.const-vc-dd100.py [DIP_MIN=35]
Writes subd-model-runs/const-vc-dd100/run-inputs/full-list.dip<DIP_MIN>.txt (format of submit_from_list.sh:
one run number per line, '#' comment lines allowed, no inline comments).
"""
import sys
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DIP_MIN = float(sys.argv[1]) if len(sys.argv) > 1 else 35.0
PILOT = {"135", "010", "068", "041", "120", "242", "316", "377", "268", "090", "100", "165",
         "038", "039", "343", "156", "286", "115", "031"}

P = pd.read_csv(ROOT / "data/params/params-list.const-vc.csv")
P["run"] = [f"{i:03d}" for i in range(len(P))]
passing = P[P.dip_int >= DIP_MIN]
keep = passing[~passing.run.isin(PILOT)]
band = keep[keep.dip_int < DIP_MIN + 5].sort_values("dip_int")
rest = keep[keep.dip_int >= DIP_MIN + 5].sort_values("run")

out = ROOT / "subd-model-runs/const-vc-dd100/run-inputs" / f"full-list.dip{DIP_MIN:g}.txt"
lines = [
    f"# const-vc-dd100 full submission: const-vc design filtered to dip_int >= {DIP_MIN:g} deg",
    "# (low-dip slabs flatten along the 100 km cutoff; pilot: flattening at 25-26 deg, none at 38).",
    f"# {len(passing)} runs pass the filter; {len(PILOT)} pilot runs already submitted -> {len(keep)} here.",
    f"# Riskiest band first ({DIP_MIN:g} <= dip < {DIP_MIN + 5:g}, {len(band)} runs, ascending dip), then the rest in run order.",
    f"# Generated by src/build-numerical-mods/make_submit_list.const-vc-dd100.py. Submit: ./submit_from_list.sh {out.name}",
    f"# --- {DIP_MIN:g} <= dip < {DIP_MIN + 5:g} ---",
    *band.run.tolist(),
    f"# --- dip >= {DIP_MIN + 5:g} ---",
    *rest.run.tolist(),
]
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out}: {len(keep)} runs ({len(band)} in the first band); excluded dip < {DIP_MIN:g}: {(P.dip_int < DIP_MIN).sum()}")
